remote-webdriver:
  image: selenium/standalone-firefox
  volumes:
    - /dev/shm:/dev/shm
  ports:
    - "4444:4444"
  expose:
    - 4444

worker:
  build: .
  container_name: mvn_workr
  links:
    - remote-webdriver
    - db
#    - kafka
#
  volumes:
    - "./dir:/usr/src/app/MongoScala/"  
  stdin_open: true
  tty: true
  entrypoint: /bin/sh

#pyshit:
#  build: py/
#  links:
#    - remote-webdriver
#    - db
#  stdin_open: true
#  tty: true
#  entrypoint: /bin/sh

db:
   image: mongo:4.2
   volumes:
      - ./db:/data/db
   ports:
      - "27017:27017"
